
import React, { useState } from 'react';

interface SetupWizardProps {
  onComplete: (config: any) => void;
}

const SetupWizard: React.FC<SetupWizardProps> = ({ onComplete }) => {
  const [step, setStep] = useState(1);
  const [isProcessing, setIsProcessing] = useState(false);
  const [installLogs, setInstallLogs] = useState<string[]>([]);
  
  const [creds, setCreds] = useState({
    url: 'https://dzpzszghvyfmmpnvhqoe.supabase.co',
    key: 'sb_publishable_RvE40bkmV3CXsLFDdUcshA_dV_FqZN8',
    instName: 'EduSync Unified'
  });

  const sanitize = (val: string) => {
    if (!val) return '';
    return val.trim()
      .replace(/^["']|["']$/g, '') 
      .replace(/[\u200B-\u200D\uFEFF]/g, ''); 
  };

  const supabaseSQL = `-- 1. DEFINE CORE TABLES (SNAKE_CASE FOR POSTGRES COMPATIBILITY)
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL, assignment TEXT, email TEXT, password TEXT, nfc_url TEXT, status TEXT DEFAULT 'Verified', last_active TEXT, designation TEXT, phone TEXT, dob DATE, blood_group TEXT, experience TEXT, yield TEXT, skills TEXT, emergency_contact TEXT, address TEXT);
CREATE TABLE IF NOT EXISTS campuses (id TEXT PRIMARY KEY, name TEXT, region TEXT, head TEXT, status TEXT DEFAULT 'Active', yield NUMERIC DEFAULT 0, clusters INT DEFAULT 0, schools INT DEFAULT 0, students INT DEFAULT 0, staff INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS clusters (id TEXT PRIMARY KEY, name TEXT, campus_id TEXT, campus_name TEXT, resource_person TEXT, rp_id TEXT, status TEXT DEFAULT 'Active');
CREATE TABLE IF NOT EXISTS schools (id TEXT PRIMARY KEY, name TEXT, cluster_id TEXT, cluster_name TEXT, campus_id TEXT, campus_name TEXT, headmaster TEXT, status TEXT DEFAULT 'Active', strength JSONB, address TEXT);
CREATE TABLE IF NOT EXISTS departments (id TEXT PRIMARY KEY, name TEXT, head TEXT, staff INT DEFAULT 0, classes JSONB, status TEXT DEFAULT 'Active', school TEXT);
CREATE TABLE IF NOT EXISTS classes (id TEXT PRIMARY KEY, name TEXT, dept_id TEXT, dept_name TEXT, total_students INT DEFAULT 0, grades JSONB, school TEXT);
CREATE TABLE IF NOT EXISTS attendance (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id TEXT, user_name TEXT, user_role TEXT, status TEXT, clock_in TIME, clock_out TIME, date DATE, location TEXT, method TEXT, marked_by TEXT, shift_label TEXT);
CREATE TABLE IF NOT EXISTS shifts (id TEXT PRIMARY KEY, label TEXT, start_time TIME, end_time TIME, grace_period INT, type TEXT, status TEXT DEFAULT 'Active');
CREATE TABLE IF NOT EXISTS shift_assignments (id TEXT PRIMARY KEY, shift_id TEXT, target_id TEXT, target_name TEXT, target_type TEXT, assigned_date DATE);
CREATE TABLE IF NOT EXISTS shift_categories (id TEXT PRIMARY KEY, label TEXT, description TEXT, color_code TEXT, status TEXT DEFAULT 'Active');

-- 2. SCHEMA MIGRATION: ENSURE COLUMN INTEGRITY
DO $$ 
BEGIN 
  -- Migration for schools
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='schools' AND column_name='address') THEN 
    ALTER TABLE schools ADD COLUMN address TEXT; 
  END IF;

  -- Migration for attendance
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='user_role') THEN 
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='role') THEN
       ALTER TABLE attendance RENAME COLUMN role TO user_role;
    ELSE
       ALTER TABLE attendance ADD COLUMN user_role TEXT; 
    END IF;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='user_name') THEN 
    ALTER TABLE attendance ADD COLUMN user_name TEXT; 
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='marked_by') THEN 
    ALTER TABLE attendance ADD COLUMN marked_by TEXT; 
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='attendance' AND column_name='shift_label') THEN 
    ALTER TABLE attendance ADD COLUMN shift_label TEXT; 
  END IF;
END $$;

-- 3. ENABLE ROW LEVEL SECURITY
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE campuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE clusters ENABLE ROW LEVEL SECURITY;
ALTER TABLE schools ENABLE ROW LEVEL SECURITY;
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_categories ENABLE ROW LEVEL SECURITY;

-- 4. DEFINE PUBLIC ACCESS POLICIES
DROP POLICY IF EXISTS "Public Users Access" ON users;
CREATE POLICY "Public Users Access" ON users FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public Campus Access" ON campuses;
CREATE POLICY "Public Campus Access" ON campuses FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public Cluster Access" ON clusters;
CREATE POLICY "Public Cluster Access" ON clusters FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public School Access" ON schools;
CREATE POLICY "Public School Access" ON schools FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public Dept Access" ON departments;
CREATE POLICY "Public Dept Access" ON departments FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public Class Access" ON classes;
CREATE POLICY "Public Class Access" ON classes FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public Attendance Access" ON attendance;
CREATE POLICY "Public Attendance Access" ON attendance FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public Shift Access" ON shifts;
CREATE POLICY "Public Shift Access" ON shifts FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public ShiftAssign Access" ON shift_assignments;
CREATE POLICY "Public ShiftAssign Access" ON shift_assignments FOR ALL USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public ShiftCat Access" ON shift_categories;
CREATE POLICY "Public ShiftCat Access" ON shift_categories FOR ALL USING (true) WITH CHECK (true);

-- 5. RELOAD SCHEMA CACHE
NOTIFY pgrst, 'reload schema';`;

  const handleVerify = async () => {
    const cleanUrlStr = sanitize(creds.url);
    const cleanKeyStr = sanitize(creds.key);

    if (!cleanUrlStr || !cleanKeyStr) {
      alert("Binding Error: Supabase URL and API Key are both mandatory.");
      return;
    }

    setIsProcessing(true);
    try {
      const baseUrl = cleanUrlStr.endsWith('/') ? cleanUrlStr.slice(0, -1) : cleanUrlStr;
      
      const response = await fetch(`${baseUrl}/rest/v1/users?limit=1`, {
        headers: { 
          'apikey': cleanKeyStr, 
          'Authorization': `Bearer ${cleanKeyStr}` 
        }
      });
      
      if (!response.ok) {
        const errorBody = await response.text();
        if (response.status === 401 || response.status === 403) {
          throw new Error(`Invalid API Key.`);
        } else if (response.status === 404) {
          throw new Error(`Table 'users' not found. Run SQL first.`);
        } else {
          throw new Error(`Handshake Failed (HTTP ${response.status}).`);
        }
      }
      
      setCreds({ ...creds, url: baseUrl, key: cleanKeyStr });
      setStep(3);
    } catch (e: any) {
      alert(e.message);
    } finally { 
      setIsProcessing(false); 
    }
  };

  const handleFullInstall = async () => {
    setIsProcessing(true);
    setInstallLogs(['[INIT] Propagating Institutional Fabric...']);
    
    const targetUrl = creds.url;
    const targetKey = creds.key;
    
    localStorage.setItem('SUPABASE_URL', targetUrl);
    localStorage.setItem('SUPABASE_KEY', targetKey);

    const dataToSync = {
      users: [
        { 
          id: 'ADMIN-001', 
          name: 'Root Administrator', 
          role: 'SUPER_ADMIN', 
          assignment: 'Global Root', 
          email: 'admin@thibyan.edu', 
          password: '1234', 
          status: 'Verified',
          dob: null 
        }
      ],
      shift_categories: [
        { id: 'SC-01', label: 'Standard Shift', description: 'Regular academic operations', color_code: '#2563eb', status: 'Active' },
        { id: 'SC-02', label: 'Exam Shift', description: 'Formal assessment periods', color_code: '#dc2626', status: 'Active' },
        { id: 'SC-03', label: 'Training Shift', description: 'Professional development sessions', color_code: '#9333ea', status: 'Active' },
        { id: 'SC-04', label: 'Special Shift', description: 'One-off institutional events', color_code: '#d97706', status: 'Active' }
      ]
    };

    try {
      for (const [table, records] of Object.entries(dataToSync)) {
        for (const record of records) {
          setInstallLogs(prev => [...prev, `[SYNC] Writing ${table}: ${record.id}...`]);
          const res = await fetch(`${targetUrl}/rest/v1/${table}?on_conflict=id`, {
            method: 'POST',
            headers: { 
              'Content-Type': 'application/json', 
              'apikey': targetKey, 
              'Authorization': `Bearer ${targetKey}`,
              'Prefer': 'resolution=merge-duplicates'
            },
            body: JSON.stringify(record)
          });
          if (!res.ok) throw new Error(`Write failed: ${await res.text()}`);
        }
      }
      setInstallLogs(prev => [...prev, '[SUCCESS] Sovereign Identity Provisioned.']);
      setTimeout(() => setStep(4), 1000);
    } catch (e: any) { 
      setInstallLogs(prev => [...prev, `[CRITICAL] ${e.message}`]); 
    } finally { 
      setIsProcessing(false); 
    }
  };

  return (
    <div className="fixed inset-0 bg-slate-950 z-[1000] flex items-center justify-center p-4">
      <div className="max-w-xl w-full bg-white/5 backdrop-blur-3xl border border-white/10 rounded-[3.5rem] p-10 text-center shadow-2xl overflow-y-auto max-h-[90vh] custom-scrollbar">
        {step === 1 && (
          <div className="space-y-8 animate-in fade-in duration-500">
            <h2 className="text-3xl font-black text-white tracking-tight">Cloud Handshake</h2>
            <div className="space-y-4 text-left">
              <InputGroup label="Supabase URL" value={creds.url} onChange={v => setCreds({...creds, url: v})} placeholder="https://xyz.supabase.co" />
              <InputGroup label="Supabase Project API Key" value={creds.key} type="password" onChange={v => setCreds({...creds, key: v})} placeholder="eyJ..." />
              <div className="bg-blue-950/40 border border-blue-500/20 p-5 rounded-2xl">
                 <p className="text-blue-400 text-[9px] font-black uppercase tracking-widest mb-1">Infrastructure Note</p>
                 <p className="text-white/60 text-[11px] leading-relaxed">System credentials pre-loaded for institutional synchronization. Tap the button below to generate your node structure.</p>
              </div>
            </div>
            <button onClick={() => setStep(2)} className="w-full py-5 bg-blue-600 text-white rounded-[1.8rem] font-black uppercase text-xs shadow-xl active:scale-95 transition-all hover:bg-blue-50">Generate SQL Schema</button>
          </div>
        )}
        {step === 2 && (
          <div className="space-y-8 animate-in slide-in-from-right-4 duration-500">
            <h2 className="text-3xl font-black text-white tracking-tight">Registry Build</h2>
            <div className="relative group">
              <pre className="text-[8px] text-slate-500 bg-black/40 p-4 rounded-xl text-left h-48 overflow-y-auto border border-white/5 custom-scrollbar">{supabaseSQL}</pre>
              <button onClick={() => { navigator.clipboard.writeText(supabaseSQL); alert("SQL Artifact Copied."); }} className="absolute top-2 right-2 px-3 py-1 bg-blue-600 text-white rounded-lg text-[8px] font-black uppercase">Copy</button>
            </div>
            <p className="text-[10px] text-amber-500 font-bold px-2">Note: If you already have tables, running this will safely add missing tables and columns.</p>
            <div className="flex gap-4">
               <button onClick={() => setStep(1)} className="px-6 py-5 bg-white/5 text-slate-400 rounded-2xl text-xs font-bold hover:text-white transition-colors">Back</button>
               <button onClick={handleVerify} disabled={isProcessing} className="flex-1 py-5 bg-emerald-600 text-white rounded-[1.8rem] font-black uppercase text-xs shadow-xl active:scale-95 transition-all">
                 {isProcessing ? 'Verifying Node...' : 'Verify SQL Deployment'}
               </button>
            </div>
          </div>
        )}
        {step === 3 && (
          <div className="space-y-8 animate-in slide-in-from-right-4">
            <div className="w-20 h-20 bg-emerald-500/20 rounded-full flex items-center justify-center text-emerald-500 text-4xl mx-auto mb-4">☁️</div>
            <h2 className="text-3xl font-black text-white tracking-tight">Deploy Node</h2>
            <button onClick={handleFullInstall} disabled={isProcessing} className="w-full py-6 bg-blue-600 text-white rounded-[2rem] font-black text-sm uppercase shadow-2xl active:scale-95">
              {isProcessing ? 'Provisioning...' : '🚀 Provision Core'}
            </button>
            <div className="bg-black/40 p-4 rounded-xl text-[9px] text-emerald-400 text-left font-mono space-y-1 h-32 overflow-y-auto border border-white/5 custom-scrollbar">
              {installLogs.map((l,i) => <p key={i}>{l}</p>)}
            </div>
          </div>
        )}
        {step === 4 && (
          <div className="space-y-8 animate-in slide-in-from-right-4">
            <h2 className="text-3xl font-black text-white tracking-tight">Identity</h2>
            <div className="space-y-2 text-left">
              <label className="text-[10px] font-black text-slate-500 uppercase tracking-widest px-2">System Name</label>
              <input type="text" value={creds.instName} onChange={e => setCreds({...creds, instName: e.target.value})} className="w-full bg-white/10 border border-white/10 rounded-2xl p-5 text-white text-sm font-bold outline-none focus:border-blue-500" />
            </div>
            <button onClick={() => setStep(5)} className="w-full py-5 bg-blue-600 text-white rounded-[1.8rem] font-black uppercase text-xs shadow-xl">Finalize Setup</button>
          </div>
        )}
        {step === 5 && (
          <div className="space-y-8 animate-in zoom-in-95">
            <div className="w-24 h-24 bg-emerald-500/20 rounded-full flex items-center justify-center text-emerald-500 text-5xl mx-auto mb-6">✓</div>
            <h2 className="text-3xl font-black text-white tracking-tight">System Live</h2>
            <p className="text-white/40 text-sm">Institutional synchronization established.</p>
            <button onClick={() => { localStorage.setItem('SYSTEM_PROVISIONED', 'true'); localStorage.setItem('APP_NAME', creds.instName); onComplete(creds); }} className="w-full py-6 bg-white text-slate-900 rounded-[2rem] font-black uppercase text-xs shadow-xl active:scale-95 transition-all hover:bg-slate-50">Enter Dashboard</button>
          </div>
        )}
      </div>
    </div>
  );
};

const InputGroup: React.FC<{ label: string, value: string, onChange: (v: string) => void, type?: string, placeholder?: string }> = ({ label, value, onChange, type = "text", placeholder }) => (
  <div className="space-y-2">
    <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest px-2">{label}</label>
    <input type={type} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="w-full bg-white/10 border border-white/10 rounded-2xl p-4 text-white text-xs font-bold outline-none focus:border-blue-500 transition-all placeholder:text-white/10" />
  </div>
);

export default SetupWizard;
